# http://blog.tgrrtt.com/exploring-the-travisci-configuration-file
sudo: required
dist: precise
language: node_js
node_js:
  - "node"
addons:
  sauce_connect:
    username: "cheriejw"
    access_key: $ACCESS_KEY
# https://docs.travis-ci.com/user/environment-variables/
notifications:
  # email: false
  email:
    on_success: always
    on_failure: never
branches:
  only:
    - master
before_install:
- sudo apt-get update -qq
after_script:
# Conditional Code...
- test $TRAVIS_PULL_REQUEST - false \
  && echo "not a pull request" \
after_success:
- test $TRAVIS_PULL_REQUEST - false \
  && git push

