# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  sass_dir: assets/css
  style: :nested

exclude: 
  - script/ # For continuous integeration script
  - [vendor] # "Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on."
