# Portfolio Settings

# Header Section
title: Cherie Woo
email: cheriejawoo@yahoo.com
description: Software Developer || Artist

menu:
# - {name: Shop My Crafts, url: '#shop', }
- {name: About Me, url: '#about'}
- {name: Projects, url: '#projects'}
- {name: Work, url: '#work'}
# - {name: Resume, url: '#resume'}
- {name: Contact, url: '#contact'}

logo: 'logo.svg'
bg-img: 'sitting.jpg'

# About Section
avatar: 'face.jpg'
blurb: <p><strong>Hi, my name is Cherie</strong> and I specialize in <b>Web Development</b>, but I hold interest in many computer science related subjects. I am a very <b>happy-go-lucky</b> kind of human and outside of code I dabble in art!</p>

skills:
- {name: Visual Design, value: 7}
- {name: Frontend Development, value: 8}
- {name: Programming, value: 6}
- {name: Database/Server-side, value: 4}
- {name: Communication, value: 7}
- {name: Progressive, value: 6}

# Projects Section
projects: 
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'laika', thumb: 'asteroid.png'}
- {name: KibbleCount, description: 'Minimize the Cost, Constrain the Calories with Linear Programming.', url: 'https://devpost.com/software/kibblecount', folder: 'kibblecount', thumb: 'homepage.jpg'}
- {name: Free-Hands Input, description: 'Using intuitive controls with gestures and voice, control a web browser and many other applications.', url: 'https://devpost.com/software/freehandsbrowser', folder: 'handsfreebrowser', thumb: 'handsfree-demo.jpg'}
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'Laika/asteroid.png'}
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'Laika/asteroid.png'}
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'Laika/asteroid.png'}
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'Laika/asteroid.png'}
- {name: Laika, description: Friendly Linode User Interface, url: 'https://devpost.com/software/laika', folder: 'Laika/asteroid.png'}